### ISSUE TITLE
No results produced after Denovo Run

### ISSUE THREAD

**Issue by xy127** [MolAICal/molaical.github.io#9]
Hello,

I set up my system and procedure same as tutorial. (protein and initial fragment is different)  But after the run finished, there is no Results folder. I did get some files produced: vmdGen.tcl, MAICGrid.dat, tmpLigands.mol2, and denovo.log. temLigands.mol2 contains 2900 molecules, mostly fragments. 

denovo.log prints

`# Project leader: Qifeng Bai, the official site of MolAICal: https://molaical.github.io or https://molaical.gitee.io #

Now generate Grids......
Now read atom, bond, etc parameters......
Total read fragments: 67.
Now read generated Grids......
Now initial starting fragment......
0    [main] INFO  net.sf.jnati.deploy.artefact.ConfigManager  - Loading global configuration
4    [main] DEBUG net.sf.jnati.deploy.artefact.ConfigManager  - Loading defaults: jar:file:/home/ubuntu/user_space/MolAICal-linux64/MolAICal_lib/cdk-2.1.1.jar!/META-INF/jnati/jnati.default-properties
5    [main] INFO  net.sf.jnati.deploy.artefact.ConfigManager  - Loading artefact configuration: jniinchi-1.03_1
6    [main] DEBUG net.sf.jnati.deploy.artefact.ConfigManager  - Loading instance defaults: jar:file:/home/ubuntu/user_space/MolAICal-linux64/MolAICal_lib/cdk-2.1.1.jar!/META-INF/jnati/jnati.instance.default-properties
8    [main] INFO  net.sf.jnati.deploy.repository.ClasspathRepository  - Searching classpath for: jniinchi-1.03_1-LINUX-AMD64
10   [main] INFO  net.sf.jnati.deploy.repository.LocalRepository  - Searching local repository for: jniinchi-1.03_1-LINUX-AMD64
10   [main] DEBUG net.sf.jnati.deploy.repository.LocalRepository  - Artefact path: /home/ubuntu/.jnati/repo/jniinchi/1.03_1/LINUX-AMD64
11   [main] INFO  net.sf.jnati.deploy.artefact.ManifestReader  - Reading manifest
36   [main] INFO  net.sf.jnati.deploy.NativeArtefactLocator  - Artefact (jniinchi-1.03_1-LINUX-AMD64) location: /home/ubuntu/.jnati/repo/jniinchi/1.03_1/LINUX-AMD64
36   [main] DEBUG net.sf.jnati.deploy.NativeLibraryLoader  - Loading library: /home/ubuntu/.jnati/repo/jniinchi/1.03_1/LINUX-AMD64/libJniInchi-1.03_1-LINUX-AMD64.so
#################################################################
Pop size: 119
Minimum molecular weight: 60;
Maximum molecular weight: 252;
Average molecular weight: 142;
Lowest affinity: 0.11 kcal/mol;
Highest affinity: 1.92 kcal/mol;
Average affinity: 0.84 kcal/mol;
#################################################################
The 1th cycle start at: 16:11:35 2023-04-20
Top 119 root ligands are chosen.
Top 11 elite ligands are chosen.
#################################################################
Pop size: 2567
Minimum molecular weight: 60;
Maximum molecular weight: 431;
Average molecular weight: 217;
Lowest affinity: 0.11 kcal/mol;
Highest affinity: 3.06 kcal/mol;
Average affinity: 1.28 kcal/mol;
#################################################################
Storing the 1th cycle result......
The 2th cycle start at: 17:13:29 2023-04-20
Top 200 root ligands are chosen.
Top 256 elite ligands are chosen.
#################################################################
Pop size: 2265
Minimum molecular weight: 60;
Maximum molecular weight: 518;
Average molecular weight: 215;
Lowest affinity: 0.11 kcal/mol;
Highest affinity: 4.01 kcal/mol;
Average affinity: 1.10 kcal/mol;
#################################################################
Storing the 2th cycle result......
'

Where is the problem?

**Comment by MolAICal** [comment]
Please see your results:
```javascript
Lowest affinity: 0.11 kcal/mol;
Highest affinity: 4.01 kcal/mol;
Average affinity: 1.10 kcal/mol;
```
The lowest affinity is not negative. It seems that it does not generate the good ligands. Please check:
1) Is the selected center point in the receptor pocket? And are the box lengths suitable?
2) Some pockets of receptors are narrow. The quantity and diversity of growth fragments are not enough. Please use Pymol or ucsf chimera to check the pocket of the receptor. If the pocket seems to be narrow when initial fragment is located in the pocket, it will not have population generation because there is no space for fragment growth.
3) At last, if you want to get results, you can increase the cutoff value for selection. Modify parameters in configure file such as "InputParFileAI.dat":
`selBindingScore				-3`

to 

`selBindingScore				3`

**Comment by xy127** [comment]
Hello, I found the center of box was set incorrectly. After changing, the binding energy become as low as -12 Kcal/mol , but I still don't get Results folder.
 The selBindingScore was still -3. I wonder where the default directory for Result is. In the input file, # moloutputdir is commented.

Please see the pasted results for denovo.log




#################################################################
Pop size: 136
Minimum molecular weight: 150;
Maximum molecular weight: 342;
Average molecular weight: 198;
Lowest affinity: -5.59 kcal/mol;
Highest affinity: -2.93 kcal/mol;
Average affinity: -3.60 kcal/mol;
#################################################################
The 1th cycle start at: 14:34:15 2023-04-21
Top 134 root ligands are chosen.
Top 13 elite ligands are chosen.
#################################################################
Pop size: 2013
Minimum molecular weight: 164;
Maximum molecular weight: 468;
Average molecular weight: 255;
Lowest affinity: -7.91 kcal/mol;
Highest affinity: -2.66 kcal/mol;
Average affinity: -4.29 kcal/mol;
#################################################################
Storing the 1th cycle result......
The 2th cycle start at: 17:10:04 2023-04-21
Top 200 root ligands are chosen.
Top 201 elite ligands are chosen.
#################################################################
Pop size: 1411
Minimum molecular weight: 192;
Maximum molecular weight: 484;
Average molecular weight: 306;
Lowest affinity: -9.50 kcal/mol;
Highest affinity: -2.97 kcal/mol;
Average affinity: -5.75 kcal/mol;
#################################################################
Storing the 2th cycle result......
The 3th cycle start at: 18:59:11 2023-04-21
Top 200 root ligands are chosen.
Top 141 elite ligands are chosen.
#################################################################
Pop size: 1078
Minimum molecular weight: 221;
Maximum molecular weight: 578;
Average molecular weight: 363;
Lowest affinity: -12.10 kcal/mol;
Highest affinity: -3.91 kcal/mol;
Average affinity: -7.41 kcal/mol;
#################################################################
Storing the 3th cycle result......
The 4th cycle start at: 20:35:32 2023-04-21
Top 200 root ligands are chosen.
Top 107 elite ligands are chosen.
#################################################################
Pop size: 823
Minimum molecular weight: 281;
Maximum molecular weight: 637;
Average molecular weight: 427;
Lowest affinity: -12.94 kcal/mol;
Highest affinity: -4.57 kcal/mol;
Average affinity: -9.03 kcal/mol;
#################################################################

**Comment by MolAICal** [comment]
Did you finish all the running cycles? For example, the number cycle of example I supplied is 30:

`numCycleGen             	30`

if you want to get results quickly, you can reduce the 30 to 3. But I recommend to 30.

**Comment by xy127** [comment]
No, the program stopped at Cycle 3, as the denovo.log suggested, while the input was set as cycle 30.  I started another run and this time stopped at Cycle 2. There was no error message at all. It just stopped there. I will try to change the input cycle to 3.  But I don't think it will solve the issue.

**Comment by MolAICal** [comment]
Please upload the log file "denovo.log" after compressing it into .zip format in Github. I can check it for you.

**Comment by xy127** [comment]
[CBLB.zip](https://github.com/MolAICal/molaical.github.io/files/11305512/CBLB.zip)
Hello, I attached all the input scripts and temporary files produced
The command I used to  run is   nohup /home/ubuntu/user_space/MolAICal-linux64/molaical.exe -denovo grow -i InputParFile.dat>denovo.log &

Thank you.

**Comment by xy127** [comment]
> And if there are no errors in "denovo.log" at all. You can try to run command directly without background:
> 
> `#> molaical.exe -denovo grow -i InputParFile.dat`
> 
> Then check whether molaical will stop at cycle 2 on linux console.
> 
> If it still stops at cycle 2, please paste the screenshot in Github. I will check it.

I am trying to test i

**Comment by xy127** [comment]
Hello,
This is the output if I use your command:  #> molaical.exe -denovo grow -i InputParFile.dat
![image](https://user-images.githubusercontent.com/68721729/233905460-e2a73c3f-eedd-45b7-9544-546b17765ad1.png)
It was not killed by me.

**Comment by MolAICal** [comment]
put input command as follow, and give me a screenshot:
`free -h`

**Comment by xy127** [comment]
> put input command as follow, and give me a screenshot: `free -h`
> 
> Besides, is your own computer? it is weird for killing operation without any warning!

![image](https://user-images.githubusercontent.com/68721729/233926653-695dea4a-0224-480b-8d1b-fddf18ebc723.png)
 
I am running script on a remote machine.

**Comment by MolAICal** [comment]
> > Did you finish all the running cycles? For example, the number cycle of example I supplied in file "InputParFileAI.dat" is 30:
> > `numCycleGen 30`
> > If you want to get results quickly, you can reduce 30 to 3. But I recommend 30 for scientific study.
> 
> After setting `numCycleGen 3` , it still have some problems, see below:
> 
> ```
> # Project leader: Qifeng Bai, the official site of MolAICal: https://molaical.github.io or https://molaical.gitee.io #
> 
> Now generate Grids......
> Now read atom, bond, etc parameters......
> Total read fragments: 67.
> Now read generated Grids......
> Now initial starting fragment......
> 0    [main] INFO  net.sf.jnati.deploy.artefact.ConfigManager  - Loading global configuration
> 4    [main] DEBUG net.sf.jnati.deploy.artefact.ConfigManager  - Loading defaults: jar:file:/home/ubuntu/user_space/MolAICal-linux64/MolAICal_lib/cdk-2.1.1.jar!/META-INF/jnati/jnati.default-properties
> 5    [main] INFO  net.sf.jnati.deploy.artefact.ConfigManager  - Loading artefact configuration: jniinchi-1.03_1
> 7    [main] DEBUG net.sf.jnati.deploy.artefact.ConfigManager  - Loading instance defaults: jar:file:/home/ubuntu/user_space/MolAICal-linux64/MolAICal_lib/cdk-2.1.1.jar!/META-INF/jnati/jnati.instance.default-properties
> 9    [main] INFO  net.sf.jnati.deploy.repository.ClasspathRepository  - Searching classpath for: jniinchi-1.03_1-LINUX-AMD64
> 20   [main] INFO  net.sf.jnati.deploy.repository.LocalRepository  - Searching local repository for: jniinchi-1.03_1-LINUX-AMD64
> 20   [main] DEBUG net.sf.jnati.deploy.repository.LocalRepository  - Artefact path: /home/ubuntu/.jnati/repo/jniinchi/1.03_1/LINUX-AMD64
> 21   [main] INFO  net.sf.jnati.deploy.artefact.ManifestReader  - Reading manifest
> 51   [main] INFO  net.sf.jnati.deploy.NativeArtefactLocator  - Artefact (jniinchi-1.03_1-LINUX-AMD64) location: /home/ubuntu/.jnati/repo/jniinchi/1.03_1/LINUX-AMD64
> 51   [main] DEBUG net.sf.jnati.deploy.NativeLibraryLoader  - Loading library: /home/ubuntu/.jnati/repo/jniinchi/1.03_1/LINUX-AMD64/libJniInchi-1.03_1-LINUX-AMD64.so
> #################################################################
> Pop size: 137
> Minimum molecular weight: 150;
> Maximum molecular weight: 342;
> Average molecular weight: 198;
> Lowest affinity: -4.78 kcal/mol;
> Highest affinity: -2.93 kcal/mol;
> Average affinity: -3.58 kcal/mol;
> #################################################################
> The 1th cycle start at: 09:35:20 2023-04-24
> Top 135 root ligands are chosen.
> Top 13 elite ligands are chosen.
> #################################################################
> Pop size: 2033
> Minimum molecular weight: 164;
> Maximum molecular weight: 470;
> Average molecular weight: 252;
> Lowest affinity: -8.00 kcal/mol;
> Highest affinity: -2.45 kcal/mol;
> Average affinity: -4.28 kcal/mol;
> #################################################################
> Storing the 1th cycle result......
> The 2th cycle start at: 12:09:28 2023-04-24
> Top 200 root ligands are chosen.
> Top 203 elite ligands are chosen.
> #################################################################
> Pop size: 1202
> Minimum molecular weight: 196;
> Maximum molecular weight: 506;
> Average molecular weight: 303;
> Lowest affinity: -9.15 kcal/mol;
> Highest affinity: -3.29 kcal/mol;
> Average affinity: -5.83 kcal/mol;
> #################################################################
> Storing the 2th cycle result......
> The 3th cycle start at: 13:32:19 2023-04-24
> Top 200 root ligands are chosen.
> Top 120 elite ligands are chosen.
> #################################################################
> Pop size: 1306
> Minimum molecular weight: 222;
> Maximum molecular weight: 606;
> Average molecular weight: 365;
> Lowest affinity: -11.36 kcal/mol;
> Highest affinity: -3.47 kcal/mol;
> Average affinity: -7.24 kcal/mol;
> #################################################################
> Storing the 3th cycle result......
> Cycle ends at: 15:16:33 2023-04-24
> Now start to output ligand grow results......
> Exception in thread "main" java.lang.NullPointerException
> 	at Denovo.Grow.LigGrow.AnalysisPOP.analyzePopulation(AnalysisPOP.java:151)
> 	at Denovo.Grow.LigGrow.MainGrow.runningGrow(MainGrow.java:229)
> 	at MolAICal.MolAICal.main(MolAICal.java:670)
> ```

Please compress your results and upload it into Github. I can help you check it.

**Comment by xy127** [comment]
> > > Did you finish all the running cycles? For example, the number cycle of example I supplied in file "InputParFileAI.dat" is 30:
> > > `numCycleGen 30`
> > > If you want to get results quickly, you can reduce 30 to 3. But I recommend 30 for scientific study.
> > 
> > 
> > After setting `numCycleGen 3` , it still have some problems, see below:
> > ```
> > # Project leader: Qifeng Bai, the official site of MolAICal: https://molaical.github.io or https://molaical.gitee.io #
> > 
> > Now generate Grids......
> > Now read atom, bond, etc parameters......
> > Total read fragments: 67.
> > Now read generated Grids......
> > Now initial starting fragment......
> > 0    [main] INFO  net.sf.jnati.deploy.artefact.ConfigManager  - Loading global configuration
> > 4    [main] DEBUG net.sf.jnati.deploy.artefact.ConfigManager  - Loading defaults: jar:file:/home/ubuntu/user_space/MolAICal-linux64/MolAICal_lib/cdk-2.1.1.jar!/META-INF/jnati/jnati.default-properties
> > 5    [main] INFO  net.sf.jnati.deploy.artefact.ConfigManager  - Loading artefact configuration: jniinchi-1.03_1
> > 7    [main] DEBUG net.sf.jnati.deploy.artefact.ConfigManager  - Loading instance defaults: jar:file:/home/ubuntu/user_space/MolAICal-linux64/MolAICal_lib/cdk-2.1.1.jar!/META-INF/jnati/jnati.instance.default-properties
> > 9    [main] INFO  net.sf.jnati.deploy.repository.ClasspathRepository  - Searching classpath for: jniinchi-1.03_1-LINUX-AMD64
> > 20   [main] INFO  net.sf.jnati.deploy.repository.LocalRepository  - Searching local repository for: jniinchi-1.03_1-LINUX-AMD64
> > 20   [main] DEBUG net.sf.jnati.deploy.repository.LocalRepository  - Artefact path: /home/ubuntu/.jnati/repo/jniinchi/1.03_1/LINUX-AMD64
> > 21   [main] INFO  net.sf.jnati.deploy.artefact.ManifestReader  - Reading manifest
> > 51   [main] INFO  net.sf.jnati.deploy.NativeArtefactLocator  - Artefact (jniinchi-1.03_1-LINUX-AMD64) location: /home/ubuntu/.jnati/repo/jniinchi/1.03_1/LINUX-AMD64
> > 51   [main] DEBUG net.sf.jnati.deploy.NativeLibraryLoader  - Loading library: /home/ubuntu/.jnati/repo/jniinchi/1.03_1/LINUX-AMD64/libJniInchi-1.03_1-LINUX-AMD64.so
> > #################################################################
> > Pop size: 137
> > Minimum molecular weight: 150;
> > Maximum molecular weight: 342;
> > Average molecular weight: 198;
> > Lowest affinity: -4.78 kcal/mol;
> > Highest affinity: -2.93 kcal/mol;
> > Average affinity: -3.58 kcal/mol;
> > #################################################################
> > The 1th cycle start at: 09:35:20 2023-04-24
> > Top 135 root ligands are chosen.
> > Top 13 elite ligands are chosen.
> > #################################################################
> > Pop size: 2033
> > Minimum molecular weight: 164;
> > Maximum molecular weight: 470;
> > Average molecular weight: 252;
> > Lowest affinity: -8.00 kcal/mol;
> > Highest affinity: -2.45 kcal/mol;
> > Average affinity: -4.28 kcal/mol;
> > #################################################################
> > Storing the 1th cycle result......
> > The 2th cycle start at: 12:09:28 2023-04-24
> > Top 200 root ligands are chosen.
> > Top 203 elite ligands are chosen.
> > #################################################################
> > Pop size: 1202
> > Minimum molecular weight: 196;
> > Maximum molecular weight: 506;
> > Average molecular weight: 303;
> > Lowest affinity: -9.15 kcal/mol;
> > Highest affinity: -3.29 kcal/mol;
> > Average affinity: -5.83 kcal/mol;
> > #################################################################
> > Storing the 2th cycle result......
> > The 3th cycle start at: 13:32:19 2023-04-24
> > Top 200 root ligands are chosen.
> > Top 120 elite ligands are chosen.
> > #################################################################
> > Pop size: 1306
> > Minimum molecular weight: 222;
> > Maximum molecular weight: 606;
> > Average molecular weight: 365;
> > Lowest affinity: -11.36 kcal/mol;
> > Highest affinity: -3.47 kcal/mol;
> > Average affinity: -7.24 kcal/mol;
> > #################################################################
> > Storing the 3th cycle result......
> > Cycle ends at: 15:16:33 2023-04-24
> > Now start to output ligand grow results......
> > Exception in thread "main" java.lang.NullPointerException
> > 	at Denovo.Grow.LigGrow.AnalysisPOP.analyzePopulation(AnalysisPOP.java:151)
> > 	at Denovo.Grow.LigGrow.MainGrow.runningGrow(MainGrow.java:229)
> > 	at MolAICal.MolAICal.main(MolAICal.java:670)
> > ```
> 
> Please compress your results and upload it into Github. I can help you check it.

[CBLB_1.zip](https://github.com/MolAICal/molaical.github.io/files/11308265/CBLB_1.zip)

**Comment by MolAICal** [comment]
> > > > Did you finish all the running cycles? For example, the number cycle of example I supplied in file "InputParFileAI.dat" is 30:
> > > > `numCycleGen 30`
> > > > If you want to get results quickly, you can reduce 30 to 3. But I recommend 30 for scientific study.
> > > 
> > > 
> > > After setting `numCycleGen 3` , it still have some problems, see below:
> > > ```
> > > # Project leader: Qifeng Bai, the official site of MolAICal: https://molaical.github.io or https://molaical.gitee.io #
> > > 
> > > Now generate Grids......
> > > Now read atom, bond, etc parameters......
> > > Total read fragments: 67.
> > > Now read generated Grids......
> > > Now initial starting fragment......
> > > 0    [main] INFO  net.sf.jnati.deploy.artefact.ConfigManager  - Loading global configuration
> > > 4    [main] DEBUG net.sf.jnati.deploy.artefact.ConfigManager  - Loading defaults: jar:file:/home/ubuntu/user_space/MolAICal-linux64/MolAICal_lib/cdk-2.1.1.jar!/META-INF/jnati/jnati.default-properties
> > > 5    [main] INFO  net.sf.jnati.deploy.artefact.ConfigManager  - Loading artefact configuration: jniinchi-1.03_1
> > > 7    [main] DEBUG net.sf.jnati.deploy.artefact.ConfigManager  - Loading instance defaults: jar:file:/home/ubuntu/user_space/MolAICal-linux64/MolAICal_lib/cdk-2.1.1.jar!/META-INF/jnati/jnati.instance.default-properties
> > > 9    [main] INFO  net.sf.jnati.deploy.repository.ClasspathRepository  - Searching classpath for: jniinchi-1.03_1-LINUX-AMD64
> > > 20   [main] INFO  net.sf.jnati.deploy.repository.LocalRepository  - Searching local repository for: jniinchi-1.03_1-LINUX-AMD64
> > > 20   [main] DEBUG net.sf.jnati.deploy.repository.LocalRepository  - Artefact path: /home/ubuntu/.jnati/repo/jniinchi/1.03_1/LINUX-AMD64
> > > 21   [main] INFO  net.sf.jnati.deploy.artefact.ManifestReader  - Reading manifest
> > > 51   [main] INFO  net.sf.jnati.deploy.NativeArtefactLocator  - Artefact (jniinchi-1.03_1-LINUX-AMD64) location: /home/ubuntu/.jnati/repo/jniinchi/1.03_1/LINUX-AMD64
> > > 51   [main] DEBUG net.sf.jnati.deploy.NativeLibraryLoader  - Loading library: /home/ubuntu/.jnati/repo/jniinchi/1.03_1/LINUX-AMD64/libJniInchi-1.03_1-LINUX-AMD64.so
> > > #################################################################
> > > Pop size: 137
> > > Minimum molecular weight: 150;
> > > Maximum molecular weight: 342;
> > > Average molecular weight: 198;
> > > Lowest affinity: -4.78 kcal/mol;
> > > Highest affinity: -2.93 kcal/mol;
> > > Average affinity: -3.58 kcal/mol;
> > > #################################################################
> > > The 1th cycle start at: 09:35:20 2023-04-24
> > > Top 135 root ligands are chosen.
> > > Top 13 elite ligands are chosen.
> > > #################################################################
> > > Pop size: 2033
> > > Minimum molecular weight: 164;
> > > Maximum molecular weight: 470;
> > > Average molecular weight: 252;
> > > Lowest affinity: -8.00 kcal/mol;
> > > Highest affinity: -2.45 kcal/mol;
> > > Average affinity: -4.28 kcal/mol;
> > > #################################################################
> > > Storing the 1th cycle result......
> > > The 2th cycle start at: 12:09:28 2023-04-24
> > > Top 200 root ligands are chosen.
> > > Top 203 elite ligands are chosen.
> > > #################################################################
> > > Pop size: 1202
> > > Minimum molecular weight: 196;
> > > Maximum molecular weight: 506;
> > > Average molecular weight: 303;
> > > Lowest affinity: -9.15 kcal/mol;
> > > Highest affinity: -3.29 kcal/mol;
> > > Average affinity: -5.83 kcal/mol;
> > > #################################################################
> > > Storing the 2th cycle result......
> > > The 3th cycle start at: 13:32:19 2023-04-24
> > > Top 200 root ligands are chosen.
> > > Top 120 elite ligands are chosen.
> > > #################################################################
> > > Pop size: 1306
> > > Minimum molecular weight: 222;
> > > Maximum molecular weight: 606;
> > > Average molecular weight: 365;
> > > Lowest affinity: -11.36 kcal/mol;
> > > Highest affinity: -3.47 kcal/mol;
> > > Average affinity: -7.24 kcal/mol;
> > > #################################################################
> > > Storing the 3th cycle result......
> > > Cycle ends at: 15:16:33 2023-04-24
> > > Now start to output ligand grow results......
> > > Exception in thread "main" java.lang.NullPointerException
> > > 	at Denovo.Grow.LigGrow.AnalysisPOP.analyzePopulation(AnalysisPOP.java:151)
> > > 	at Denovo.Grow.LigGrow.MainGrow.runningGrow(MainGrow.java:229)
> > > 	at MolAICal.MolAICal.main(MolAICal.java:670)
> > > ```
> > 
> > 
> > Please compress your results and upload it into Github. I can help you check it.
> 
> [CBLB_1.zip](https://github.com/MolAICal/molaical.github.io/files/11308265/CBLB_1.zip)

Could you delete file "tmpLigands.mol2" in your workdir and re-run MolAICal for denovo?

If you still find something wrong, please compress your results and upload into Github.

**Comment by MolAICal** [comment]
Is your problem solved by following the above suggestion?
